on:
  push:
    branches:
      - master
name: Build and deploy on push
jobs:
  build:
    name: Build and deploy on push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: 'recursive'
    - uses: actions/cache@v2
      id: cache
      with:
        path: zola
        key: zola-11.0
    - name: Install Zola
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
          mkdir zola
          wget -q -O - "https://github.com/getzola/zola/releases/download/v0.11.0/zola-v0.11.0-x86_64-unknown-linux-gnu.tar.gz" | tar xzf - -C zola
    - name: Run Zola
      run: ./zola/zola build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        allow_empty_commit: false
